de_fscale: 2.
de_prob_default: .2
de_prob: [.05, .2, .5]
coverage: [100, 1000, 10000]
batch_facscale: 0.4
n_cells: 4000
n_reps: 5
n_batches: 4
frac_shared: .5
methods: ["scDEF", "scDEF_un"]
layer_sizes: [100, 60, 30, 10, 1]
default_tau: 1000
default_mu: 1000
default_kappa: 1.
tau: [10, 100, 1000]
mu: [10, 100, 1000]
kappa: [.3, 1., 10.]
