site_name: scDEF

theme:
  name: "material"
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: indigo
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: indigo
  favicon: assets/images/icon.svg
  logo: assets/images/icon.svg
  custom_dir: docs/overrides/


plugins:
  - search
  - mkdocs-jupyter:
      execute: false
      include_source: true
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: false
            show_root_heading: true

nav:
  - Getting started: index.md
  - Examples:
    - Basic usage: examples/basicusage.md
    - Getting started with 3k PBMCs: examples/scdef-pbmcs3k.ipynb
    - Cell type hierarchies in a whole adult animal: examples/scdef-planaria.ipynb
    - Integrating two batches of PBMCs: examples/scdef-pbmcs-2batches.ipynb
    - Identifying interferon-response between two batches of PBMCs: examples/scdef-ifn.ipynb
  - API Reference: api.md

repo_name: scDEF
repo_url: https://github.com/cbg-ethz/scDEF

watch:
  - src/scdef
