"""Tooling utilities for scDEF.
"""

from .hierarchy import (
    get_hierarchy,
    make_hierarchies,
    make_biological_hierarchy,
    make_technical_hierarchy,
    make_global_hierarchy,
    compute_hierarchy_scores,
    add_l0_lineage_aggregate_scores,
    find_sensible_top_layer,
    find_sensible_top_factors,
)
from .factor import (
    assign_confident,
    filter_factors,
    batch_structure_report,
    annotate_factors,
    get_factor_annotations,
    compute_within_group_pairwise_dissimilarity,
    factor_diagnostics,
    get_obs_score_rankings,
    get_obs_value_specific_factors,
    set_cell_entropies,
    set_confident_signatures,
    get_stored_confident_signatures,
    set_factor_signatures,
    get_confident_signatures,
    set_technical_factors,
    set_batch_technical_factors,
    factor_batch_correction,
    drop_technical,
    get_technical_factors,
    get_batch_technical_factors,
    set_global_factors,
    get_technical_signature,
    get_global_signature,
    get_biological_signature,
    gsea,
    umap,
    multilayer_umap,
)
from .trajectory import (
    multilevel_paga,
    build_differentiation_paths,
    build_transition_paths,
    score_paths,
)
from .batch import (
    get_batch_specific_genes_from_gene_scale,
    get_factor_batch_gene_scale_affinity,
)
from .lineage import get_lineage_factors, get_global_factors

# `filter` is the ergonomic alias; the function is defined as
# `filter_factors` so it does not shadow the builtin inside factor.py.
filter = filter_factors

__all__ = [
    "assign_confident",
    "filter",
    "filter_factors",
    "batch_structure_report",
    "annotate_factors",
    "get_factor_annotations",
    "multilayer_umap",
    "get_hierarchy",
    "make_hierarchies",
    "make_biological_hierarchy",
    "make_technical_hierarchy",
    "make_global_hierarchy",
    "compute_within_group_pairwise_dissimilarity",
    "factor_diagnostics",
    "get_obs_score_rankings",
    "get_obs_value_specific_factors",
    "set_cell_entropies",
    "set_confident_signatures",
    "get_stored_confident_signatures",
    "set_factor_signatures",
    "get_confident_signatures",
    "set_technical_factors",
    "set_batch_technical_factors",
    "factor_batch_correction",
    "drop_technical",
    "get_technical_factors",
    "get_batch_technical_factors",
    "set_global_factors",
    "get_technical_signature",
    "get_global_signature",
    "get_biological_signature",
    "gsea",
    "compute_hierarchy_scores",
    "add_l0_lineage_aggregate_scores",
    "find_sensible_top_layer",
    "find_sensible_top_factors",
    "umap",
    "build_differentiation_paths",
    "build_transition_paths",
    "score_paths",
    "multilevel_paga",
    "get_batch_specific_genes_from_gene_scale",
    "get_factor_batch_gene_scale_affinity",
    "get_lineage_factors",
    "get_global_factors",
]
