seed: 42
de_fscale: [.5, 2.]
de_prob: .2
n_cells: 4000
n_reps: 5
methods: ["scDEF_un", "PCA", "NMF", "scHPF", "nSBM", "fscLVM"]
metrics:
    - "Cell Type ARI"
    - "Cell Type ASW"
    - "Hierarchy accuracy"
    - "Hierarchical signature consistency"
    - "Signature sparsity"
    - "Signature accuracy"