de_fscale: 2.
de_prob_default: .2
de_prob: [.05, .2, .5]
batch_facscale: 0.4
n_cells: 4000
n_reps: 5
n_batches: 4
frac_shared: .5
hierarchy_weight: [0.1, 0.5, 1.0, 2.0, 5.0, 10.0]
brd_strength: [0.1, 1.0, 10.0, 100.0]
brd_mean: [0.1, 1.0, 10.0, 100.0]
metrics:
    - "Cell Type ARI"
    - "Cell Type ASW"
    - "Batch ARI"
    - "Batch ASW"
    - "Hierarchy accuracy"
    - "Hierarchical signature consistency"
    - "Signature sparsity"
    - "Signature accuracy"
