de_fscale: 2.
de_prob_default: .2
de_prob: [.05, .2, .5]
batch_facscale: 0.4
n_cells: 4000
n_reps: 5
n_batches: 4
frac_shared: .5
tau: [0.1, 1., 10., 100.]
mu: [0.1, 1., 10., 100.]
kappa: [0.1, 1., 10., 20., 50., 100.]
metrics:
    - "Cell Type ARI"
    - "Cell Type ASW"
    - "Batch ARI"
    - "Batch ASW"    
    - "Hierarchy accuracy"
    - "Hierarchical signature consistency"
    - "Signature sparsity"
    - "Signature accuracy"