de_fscale: 2.
de_prob_default: .2
de_prob: [.05, .2, .5]
batch_facscale: 0.4
n_cells: 4000
n_reps: 5
n_batches: 4
frac_shared: .5
methods: ["scDEF", "scDEF_un"]
layer_sizes: [100, 60, 30, 10, 1]
default_tau: 0.01
default_mu: 0.01
tau: [0.01, 0.1, 0.001, 1.]
mu: [0.01, 0.1, 0.001, 1.]