de_fscale: 2.
de_prob: .2
batch_facscale: 0.4
n_cells: 4000
n_reps: 5
n_batches: 4
frac_shared: .5
n_layers: [1, 2, 3, 4, 5]
decay_factors: [1.5, 2, 2.5, 3]
metrics:
    - "Cell Type ARI"
    - "Cell Type ASW"
    - "Batch ARI"
    - "Batch ASW"    
    - "Hierarchy accuracy"
    - "Hierarchical signature consistency"
    - "Signature sparsity"
    - "Signature accuracy"