data_path: '/cluster/work/bewi/members/pedrof/scdef_revisions/init_data/cnvs/all_cells.h5ad'
annotations_path: '/cluster/work/bewi/members/pedrof/scdef_revisions/init_data/cnvs/annot.csv'
donor_1: 'SPECTRUM-OV-026'
celltype_1: 'Ovarian.cancer.cell'
donor_2: 'SPECTRUM-OV-082'
celltype_2: 'Fibroblast'
methods: ["scDEF", "PCA", "NMF", "scHPF", "scVI", "Harmony", "Scanorama", "nSBM", "fscLVM"]
seed: 42
min_genes: 200
min_cells: 3
genes_to_remove: ['MALAT1']
n_top_genes: 4000
metrics:
    - "Cell Type ARI"
    - "Cell Type ASW"
    - "Batch ARI"
    - "Batch ASW"
    - "Hierarchy accuracy"
    - "Hierarchical signature consistency"
    - "Signature sparsity"
    - "Signature accuracy"
