data_path: 'data/planaria/raw_inputs/'
markers_path: 'data/planaria/planaria_marker_genes.csv'
gene_names_fname: 'data/planaria/planaria_named_genes.csv'
methods: ["scDEF_un", "PCA", "NMF", "scHPF", "scVI", "Harmony", "Scanorama", "nSBM", "fscLVM"]
seed: 42
min_genes: 200
min_cells: 3
genes_to_remove: ['MALAT1']
n_top_genes: 4000
metrics:
    - "Cell Type ARI"
    - "Cell Type ASW"
    - "Hierarchy accuracy"
    - "Hierarchical signature consistency"
    - "Signature sparsity"
    - "Signature accuracy"
