data_path: 'visium/'
data_fname: 'CytAssist_FFPE_Human_Breast_Cancer_filtered_feature_bc_matrix.h5'
methods: ["scDEF_un"]
seed: 42
min_genes: 200
min_cells: 3
genes_to_remove: ['MALAT1']
n_top_genes: 4000
metrics:
    - "Hierarchical signature consistency"
    - "Signature sparsity"